//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanonStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill_details
    {
        public int IdBill { get; set; }
        public int IdProduct { get; set; }
        public Nullable<int> Quality { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int Id { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Product Product { get; set; }
    }
}
