//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanonStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Bills = new HashSet<Bill>();
        }
        [Required]
        public int id { get; set; }
        [Required]
        [RegularExpression("[a-zA-Z ]*$", ErrorMessage = "Only letters")]
        public string Name { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        [RegularExpression("[0-9]{10}", ErrorMessage = "Must be 10 digits ")]
        public string Phone { get; set; }
        [Required]
        public Nullable<System.DateTime> DayOfBirth { get; set; }
        [Required]
        [RegularExpression("[a-zA-Z ]*$", ErrorMessage = "Only letters")]
        public string UserName { get; set; }
        [Required]
        [RegularExpression("[0-9]{3}", ErrorMessage = "Must be 3 digits")]
        public string Password { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
    }
}
