//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanonStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Canon_StoreEntities4 : DbContext
    {
        public Canon_StoreEntities4()
            : base("name=Canon_StoreEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Bill_details> Bill_details { get; set; }
        public virtual DbSet<Bill_Status> Bill_Status { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Emloyee> Emloyees { get; set; }
        public virtual DbSet<Mount_Product> Mount_Product { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Storage> Storages { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Type_Product> Type_Product { get; set; }
    }
}
